/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

const sidebars = {
  tutorialSidebar: [
    {
      type: "html",
      value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`, // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "doc",
      id: "sidebars",
    },
    {
      type: "doc",
      id: "versioning",
    },
    {
      type: "category",
      label: "Customization",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "customization",
        },
      ],
    },
  ],
  qovery: [
    {
      type: "category",
      label: "Qovery",
      link: {
        type: "generated-index",
        title: "Qovery API",
        description:
          "Qovery Product Team: support+api+documentation@qovery.com",
        slug: "/category/qovery-api",
      },
      items: require("./docs/qovery/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
